package org.usfirst.frc3566.PneumaticJiwonDec7.commands;

import org.usfirst.frc3566.PneumaticJiwonDec7.Robot;

import edu.wpi.first.wpilibj.command.Command;

public class climbNOW extends Command {
	 public climbNOW() {

		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		        requires(Robot.runClimber);

		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		    }

		    // Called just before this Command runs the first time
		    protected void initialize() {
		    	
		    	Robot.runClimber.climbOK();
		    
		    }

		    // Called repeatedly when this Command is scheduled to run
		    protected void execute() {
		    }
	@Override
	protected boolean isFinished() {
		// TODO Auto-generated method stub
		return false;
	}

}
