package org.usfirst.frc3566.PneumaticJiwonDec7.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3566.PneumaticJiwonDec7.OI;
import org.usfirst.frc3566.PneumaticJiwonDec7.Robot;

public class runFastorSlow extends Command {
	public OI oi;
	
	 public runFastorSlow() {
		 	oi = new OI();
		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		        requires(Robot.runClimber);

		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		    }

		    // Called just before this Command runs the first time
		    protected void initialize() {
		    	
		    	Robot.runClimber.climbFastorSlow(oi.getYValue());;
		    
		    }
		    protected void execute() {
		    }
	@Override
	protected boolean isFinished() {
		// TODO Auto-generated method stub
		
		return false;
	}

}
