// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.GearDeliveryMechanismCode1Jan12;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */;


public class RobotMap {
	
    public static final double GEAR_DELIVERY_MOTOR_SPEED_BASIC = 0.7;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainCANTalon0Right;
    public static CANTalon driveTrainCANTalon1Left;
    public static RobotDrive driveTrainRobotDrive2Motor;
    public static CANTalon gearDeliverySystemCANTalon2;
    public static DigitalInput gearDeliverySystemLimitSwitch0;
    public static DigitalInput gearDeliverySystemLimitSwitch1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainCANTalon0Right = new CANTalon(0);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 0 Right", driveTrainCANTalon0Right);
        
        driveTrainCANTalon1Left = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 1 Left", driveTrainCANTalon1Left);
        
        driveTrainRobotDrive2Motor = new RobotDrive(driveTrainCANTalon1Left, driveTrainCANTalon0Right);
        
        driveTrainRobotDrive2Motor.setSafetyEnabled(true);
        driveTrainRobotDrive2Motor.setExpiration(0.1);
        driveTrainRobotDrive2Motor.setSensitivity(0.5);
        driveTrainRobotDrive2Motor.setMaxOutput(1.0);
        driveTrainRobotDrive2Motor.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveTrainRobotDrive2Motor.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        gearDeliverySystemCANTalon2 = new CANTalon(2);
        LiveWindow.addActuator("GearDeliverySystem", "CAN Talon 2", gearDeliverySystemCANTalon2);
        
        gearDeliverySystemLimitSwitch0 = new DigitalInput(0);
        LiveWindow.addSensor("GearDeliverySystem", "Limit Switch 0", gearDeliverySystemLimitSwitch0);
        
        gearDeliverySystemLimitSwitch1 = new DigitalInput(1);
        LiveWindow.addSensor("GearDeliverySystem", "Limit Switch 1", gearDeliverySystemLimitSwitch1);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
