// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3566.MecanumDriveJan21.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3566.MecanumDriveJan21.FishyCam;
import org.usfirst.frc3566.MecanumDriveJan21.Robot;
import org.usfirst.frc3566.MecanumDriveJan21.VisionValues;
import org.usfirst.frc3566.MecanumDriveJan21.subsystems.MecanumDriveTrain.Direction;

/**
 *
 */
public class AutonomousLiftFront extends Command {
	private boolean finished;
	private long endTimer;

	// this is the autonomous command for when there is a lift in front of the
	// robot
	public AutonomousLiftFront() {

	}

	protected void initialize() {
		finished = false;
		Robot.mecanumDriveTrain.driveTrainForward(0.2);
		endTimer = System.currentTimeMillis()+2000;// + 2000;
	}

	protected void execute() {
		if (System.currentTimeMillis() >= endTimer) {
			finished = true;
			Robot.mecanumDriveTrain.stopDriveTrain();
			new DeliverGear().start();
		} else {
			Robot.mecanumDriveTrain.driveTrainForward(0.2);
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		// when detected target area is big enough, calls the command to stop
		return finished;
	}

	// Called once after isFinished returns true
	protected void end() {

	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		Robot.mecanumDriveTrain.stopDriveTrain();
	}
}
