// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.MecanumDriveJan21.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.MecanumDriveJan21.Robot;
import org.usfirst.frc3566.MecanumDriveJan21.RobotMap;

/**
 *
 */
public class AutonomousLiftFront extends Command {
	
	private double idealTargetArea;
	
    public void AutonomousCommand() {
    	idealTargetArea = RobotMap.idealVerticalTargetArea;
    }

    public boolean checkIfInRange(){
    	System.out.println(Robot.camA.avgDetectedVerticalTargetArea);
    	//System.out.println(" hey "+idealTargetArea);
    	if(Robot.camA.avgDetectedVerticalTargetArea>RobotMap.idealVerticalTargetArea){
    		return true;
    	}else{
    		return false;
    	}
    }
    
    protected void initialize() {
    }

    protected void execute() {
    	Robot.mecanumDriveTrain.driveTrainForward(0.1);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return checkIfInRange();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.mecanumDriveTrain.stopDriveTrain();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
