// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3566.MecanumDriveJan21.commands;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.MecanumDriveJan21.Robot;
import org.usfirst.frc3566.MecanumDriveJan21.RobotMap;

/**
 *
 */
public class DriveWithJoystick extends Command {

    RobotDrive myDrive;

    public DriveWithJoystick() {

	requires(Robot.mecanumDriveTrain);
	myDrive = RobotMap.mecanumDriveTrainRobotDrive;
    }

    // Called just before this Command runs the first time
    protected void initialize() {
	myDrive.mecanumDrive_Cartesian(0.0, 0.0, 0.0, 0.0);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
	myDrive.mecanumDrive_Cartesian(0,
		Robot.oi.driveTrainJoystick.getRawAxis(1) * -1, Robot.oi.getRotation(), 0);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
	return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
