// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.MecanumDriveJan21;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon mecanumDriveTrainTalonSRX1;
    public static CANTalon mecanumDriveTrainTalonSRX2;
    public static CANTalon mecanumDriveTrainTalonSRX3;
    public static CANTalon mecanumDriveTrainTalonSRX4;
    public static RobotDrive mecanumDriveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        mecanumDriveTrainTalonSRX1 = new TalonSRX(0);
        LiveWindow.addActuator("MecanumDriveTrain", "TalonSRX 1", (TalonSRX) mecanumDriveTrainTalonSRX1);
        
        mecanumDriveTrainTalonSRX2 = new TalonSRX(1);
        LiveWindow.addActuator("MecanumDriveTrain", "TalonSRX 2", (TalonSRX) mecanumDriveTrainTalonSRX2);
        
        mecanumDriveTrainTalonSRX3 = new TalonSRX(2);
        LiveWindow.addActuator("MecanumDriveTrain", "TalonSRX 3", (TalonSRX) mecanumDriveTrainTalonSRX3);
        
        mecanumDriveTrainTalonSRX4 = new TalonSRX(3);
        LiveWindow.addActuator("MecanumDriveTrain", "TalonSRX 4", (TalonSRX) mecanumDriveTrainTalonSRX4);
        
        mecanumDriveTrainRobotDrive = new RobotDrive(mecanumDriveTrainTalonSRX1, mecanumDriveTrainTalonSRX4,
              mecanumDriveTrainTalonSRX2, mecanumDriveTrainTalonSRX3);
        
        mecanumDriveTrainRobotDrive.setSafetyEnabled(true);
        mecanumDriveTrainRobotDrive.setExpiration(0.1);
        mecanumDriveTrainRobotDrive.setSensitivity(0.5);
        mecanumDriveTrainRobotDrive.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
